---

#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

anchorLinks:
  - link: &grafana-home
      url: "https://grafana.com/"
      params: "time"

#------------------------------------------------------------------------------
# Panel Config

cellIdPreamble: "cell-"
cells: 
  peer1:
    dataRef: "R-RU-IAP1 - grafana: Operational status for peer 178.176.133.56"
#    label:
#      separator: "cr"
#      units: "ops"
#      decimalPoints: 0
    fillColor:
      gradientMode: "hue"
      thresholds:
        - {color: "red", level: 0}
        - {color: "green", level: 1}
    fillLevel:
      # The optional data value at or below which the fillLevel will be set to 0%.
      thresholdOffValue: 0

      # These terms define the conversion from incoming data values to percent-fill.
      thresholdLwrValue: 0
      thresholdLwrFillPercent: 0
      thresholdUprValue: 900
      thresholdUprFillPercent: 100
      fillDirection: 'bottomToTop'
